In [5]:
import pandas as pd
import numpy as np

# Series

# Create a series

arr = np.array([1, 2, 3, 4, 5])

s = pd.Series(arr)

print(s)

print(type(s))

# Set index

s = pd.Series(arr, index=['a', 'b', 'c', 'd', 'e'])

print(s)

# Create a series from a dictionary

d = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

s = pd.Series(d)

print(s)

# DataFrames

# Create a DataFrame

data = {
    'column1': [1, 2, 3, 4, 5],
    'column2': [10, 20, 30, 40, 50],
    'column3': ['a', 'b', 'c', 'd', 'e']
}

df = pd.DataFrame(data)

print(df)

# Set index

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D', 'E'])

print(df)

# Accessing elements

# Access a column

print(df['column1'])

# Access multiple columns

print(df[['column1', 'column2']])

# Access a row

print(df.loc['A'])

# Access multiple rows

print(df.loc[['A', 'B']])

# Access a specific element

print(df.loc['A', 'column1'])

# Access a specific element using index

print(df.iloc[0, 0])

# Access a specific element using column name

print(df.at['A', 'column1'])

# Access a specific element using column index

print(df.iat[0, 0])

# Data Manipulation

# Add a new column

df['column4'] = [100, 200, 300, 400, 500]

print(df)

# Add a new row

df.loc['F'] = [6, 60, 'f', 600]

print(df)

# Drop a column

df.drop('column4', axis=1,inplace=True)

print(df)

# Drop a row

df.drop('F', axis=0,inplace=True)

print(df)

print(df.describe())

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
   column1  column2 column3
0        1       10       a
1        2       20       b
2        3       30       c
3        4       40       d
4        5       50       e
   column1  column2 column3
A        1       10       a
B        2       20       b
C        3       30       c
D        4       40       d
E        5       50       e
A    1
B    2
C    3
D    4
E    5
Name: column1, dtype: int64
   column1  column2
A        1       10
B        2       20
C        3       30
D        4       40
E        5       50
column1     1
column2    10
column3     a
Name: A, dtype: object
   column1  column2 column3
A        1       10       a
B        2       20       b
1
1
1
1
   column1  column2 column3  column4
A        1       10       a      100
B        2       20       b      200
C        3       30       c      300
D        4       40       d      400
E        5       50       e      500
   column1  column2 column3  column4
A        1       10       a      100
B        2       20       b      200
C        3       30       c      300
D        4       40       d      400
E        5       50       e      500
F        6       60       f      600
   column1  column2 column3
A        1       10       a
B        2       20       b
C        3       30       c
D        4       40       d
E        5       50       e
F        6       60       f
   column1  column2 column3
A        1       10       a
B        2       20       b
C        3       30       c
D        4       40       d
E        5       50       e
        column1    column2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000